#DEFINE wdFormatDocument	            0
#DEFINE wdFormatDocument97	            0
#DEFINE wdFormatDocumentDefault	            16
#DEFINE wdFormatDOSText	                    4
#DEFINE wdFormatDOSTextLineBreaks	    5
#DEFINE wdFormatEncodedText	            7
#DEFINE wdFormatFilteredHTML	            10
#DEFINE wdFormatFlatXML	                    19
#DEFINE wdFormatFlatXMLMacroEnabled	    20
#DEFINE wdFormatFlatXMLTemplate	            21
#DEFINE wdFormatFlatXMLTemplateMacroEnabled 22
#DEFINE wdFormatHTML	                    8
#DEFINE wdFormatPDF	                    17
#DEFINE wdFormatRTF	                    6
#DEFINE wdFormatTemplate	            1
#DEFINE wdFormatTemplate97	            1
#DEFINE wdFormatText	                    2
#DEFINE wdFormatTextLineBreaks	            3
#DEFINE wdFormatUnicodeText	            7
#DEFINE wdFormatWebArchive	            9
#DEFINE wdFormatXML	                    11
#DEFINE wdFormatXMLDocument	            12
#DEFINE wdFormatXMLDocumentMacroEnabled	    13
#DEFINE wdFormatXMLTemplate 	            14
#DEFINE wdFormatXMLTemplateMacroEnabled	    15
#DEFINE wdFormatXPS	                    18